# Generated by Django 5.0.6 on 2024-07-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_side', '0002_remove_booking_checked_in_tracker_and_more'),
        ('interactions', '0004_selections_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='selections',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel_side.hotel'),
            preserve_default=False,
        ),
    ]
