# Generated by Django 5.0.6 on 2024-07-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_side', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checked_in_tracker',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checked_out_tracker',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_side.room'),
        ),
    ]
