# Generated by Django 5.0.6 on 2024-07-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_side', '0002_remove_booking_checked_in_tracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('initiated', 'Initiated'), ('failed', 'Failed'), ('refunding', 'Refunding'), ('refunded', 'Refunded'), ('unpaid', 'Unpaid'), ('expired', 'Expired')], default='paid', max_length=100),
        ),
    ]
