# Generated by Django 5.0.6 on 2024-07-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_side', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.ManyToManyField(to='hotel_side.room'),
        ),
    ]
