# Generated by Django 5.0.6 on 2024-07-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_side', '0005_remove_booking_room_booking_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=5),
        ),
    ]
