# Generated by Django 5.0.6 on 2024-07-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='is_hotel',
        ),
        migrations.AddField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('hotel', 'HOTEL'), ('user', 'USER'), ('admin', 'ADMIN')], default='USER', max_length=100),
        ),
    ]
